<?php 
$title = 'Privacy Policy';
require_once 'includes/header.php'; 
?>

<div class="max-w-7xl mx-auto py-6 sm:px-6 lg:px-8">
    <div class="px-4 py-6 sm:px-0">
        <h1 class="text-3xl font-bold text-gray-900 mb-2">Data Privacy Policy</h1>
        <p class="text-gray-600 mb-8">Last updated: <?php echo date('F j, Y'); ?></p>
        
        <div class="prose max-w-none">
            <!-- Introduction -->
            <div class="mb-8">
                <h2 class="text-2xl font-bold mb-4">1. Introduction</h2>
                <p class="text-gray-600 mb-4">
                    giskids ("we," "our," or "us") is committed to protecting your privacy and ensuring the security of your personal information. This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you use our software solutions and services.
                </p>
                <p class="text-gray-600">
                    By using our services, you consent to the data practices described in this policy. If you do not agree with the practices described in this policy, please do not use our services.
                </p>
            </div>

            <!-- Information We Collect -->
            <div class="mb-8">
                <h2 class="text-2xl font-bold mb-4">2. Information We Collect</h2>
                
                <div class="mb-6">
                    <h3 class="text-xl font-semibold mb-3">2.1 Personal Information</h3>
                    <p class="text-gray-600 mb-3">We may collect the following types of personal information:</p>
                    <ul class="list-disc pl-6 space-y-2 text-gray-600">
                        <li>Name, email address, and contact information</li>
                        <li>Job title and company information</li>
                        <li>Login credentials and authentication data</li>
                        <li>Payment and billing information</li>
                        <li>Communication preferences</li>
                    </ul>
                </div>

                <div class="mb-6">
                    <h3 class="text-xl font-semibold mb-3">2.2 Technical Information</h3>
                    <ul class="list-disc pl-6 space-y-2 text-gray-600">
                        <li>IP addresses and device identifiers</li>
                        <li>Browser type and version</li>
                        <li>Operating system information</li>
                        <li>Usage patterns and analytics data</li>
                        <li>Error logs and system performance data</li>
                    </ul>
                </div>

                <div class="mb-6">
                    <h3 class="text-xl font-semibold mb-3">2.3 Business Data</h3>
                    <ul class="list-disc pl-6 space-y-2 text-gray-600">
                        <li>Data you input into our systems</li>
                        <li>Configuration settings and preferences</li>
                        <li>Reports and analytics generated by our systems</li>
                        <li>Integration data from third-party services</li>
                    </ul>
                </div>
            </div>

            <!-- How We Use Information -->
            <div class="mb-8">
                <h2 class="text-2xl font-bold mb-4">3. How We Use Your Information</h2>
                <p class="text-gray-600 mb-4">We use the collected information for the following purposes:</p>
                <ul class="list-disc pl-6 space-y-2 text-gray-600">
                    <li>Provide, maintain, and improve our software solutions</li>
                    <li>Process transactions and manage billing</li>
                    <li>Provide customer support and technical assistance</li>
                    <li>Send important updates and notifications</li>
                    <li>Analyze usage patterns to improve our services</li>
                    <li>Ensure security and prevent fraud</li>
                    <li>Comply with legal obligations</li>
                    <li>Communicate about new features and services (with your consent)</li>
                </ul>
            </div>

            <!-- Data Sharing -->
            <div class="mb-8">
                <h2 class="text-2xl font-bold mb-4">4. Data Sharing and Disclosure</h2>
                <p class="text-gray-600 mb-4">We do not sell, trade, or otherwise transfer your personal information to third parties except in the following circumstances:</p>
                
                <div class="mb-6">
                    <h3 class="text-xl font-semibold mb-3">4.1 Service Providers</h3>
                    <p class="text-gray-600">We may share information with trusted third-party service providers who assist us in operating our services, such as hosting providers, payment processors, and analytics services.</p>
                </div>

                <div class="mb-6">
                    <h3 class="text-xl font-semibold mb-3">4.2 Legal Requirements</h3>
                    <p class="text-gray-600">We may disclose information when required by law, court order, or government regulation, or to protect our rights and the safety of our users.</p>
                </div>

                <div class="mb-6">
                    <h3 class="text-xl font-semibold mb-3">4.3 Business Transfers</h3>
                    <p class="text-gray-600">In the event of a merger, acquisition, or sale of assets, your information may be transferred to the new entity.</p>
                </div>
            </div>

            <!-- Data Security -->
            <div class="mb-8">
                <h2 class="text-2xl font-bold mb-4">5. Data Security</h2>
                <p class="text-gray-600 mb-4">We implement appropriate technical and organizational measures to protect your personal information:</p>
                <ul class="list-disc pl-6 space-y-2 text-gray-600">
                    <li>Industry-standard encryption for data in transit and at rest</li>
                    <li>Regular security audits and vulnerability assessments</li>
                    <li>Access controls and authentication mechanisms</li>
                    <li>Employee training on data protection practices</li>
                    <li>Incident response procedures</li>
                    <li>Regular data backups and recovery procedures</li>
                </ul>
            </div>

            <!-- Data Retention -->
            <div class="mb-8">
                <h2 class="text-2xl font-bold mb-4">6. Data Retention</h2>
                <p class="text-gray-600 mb-4">We retain your personal information for as long as necessary to:</p>
                <ul class="list-disc pl-6 space-y-2 text-gray-600">
                    <li>Provide our services to you</li>
                    <li>Comply with legal obligations</li>
                    <li>Resolve disputes and enforce agreements</li>
                    <li>Maintain business records for legitimate purposes</li>
                </ul>
                <p class="text-gray-600 mt-4">When data is no longer needed, we securely delete or anonymize it according to our data retention policies.</p>
            </div>

            <!-- Your Rights -->
            <div class="mb-8">
                <h2 class="text-2xl font-bold mb-4">7. Your Rights</h2>
                <p class="text-gray-600 mb-4">You have the following rights regarding your personal information:</p>
                <ul class="list-disc pl-6 space-y-2 text-gray-600">
                    <li><strong>Access:</strong> Request a copy of your personal information</li>
                    <li><strong>Correction:</strong> Request correction of inaccurate information</li>
                    <li><strong>Deletion:</strong> Request deletion of your personal information</li>
                    <li><strong>Portability:</strong> Request transfer of your data to another service</li>
                    <li><strong>Objection:</strong> Object to processing of your personal information</li>
                    <li><strong>Restriction:</strong> Request restriction of processing</li>
                </ul>
                <p class="text-gray-600 mt-4">To exercise these rights, please contact us at <a href="mailto:privacy@giskids.com" class="text-blue-600 hover:underline">privacy@giskids.com</a>.</p>
            </div>

            <!-- Contact Information -->
            <div class="mb-8">
                <h2 class="text-2xl font-bold mb-4">8. Contact Us</h2>
                <p class="text-gray-600 mb-4">If you have any questions about this Privacy Policy or our data practices, please contact us:</p>
                <div class="bg-gray-50 p-6 rounded-lg">
                    <p class="text-gray-700 mb-2"><strong>Email:</strong> <a href="mailto:privacy@giskids.com" class="text-blue-600 hover:underline">privacy@giskids.com</a></p>
                    <p class="text-gray-700 mb-2"><strong>Phone:</strong> <a href="tel:+639765330516" class="text-blue-600 hover:underline">+63 976 533 0516</a></p>
                    <p class="text-gray-700 mb-2"><strong>Address:</strong> Quezon City, Philippines</p>
                    <p class="text-gray-700"><strong>Data Protection Officer:</strong> <a href="mailto:dpo@giskids.com" class="text-blue-600 hover:underline">dpo@giskids.com</a></p>
                </div>
            </div>
        </div>
    </div>
</div>

<?php require_once 'includes/footer.php'; ?>